#!/bin/bash

tmux new-session -Ad -s 'dev' -n 'main'
tmux split-window -v -t 0 'htop'
tmux split-window -h -t 0 
tmux split-window -h -t 2
tmux split-window -v -t 3
tmux new-window 'htop'
tmux select-window -t 1
tmux -2 attach-session -d
