#!/bin/bash

cmd="$2"
interval="$1"

if [ -z "$cmd" ] || [ -z "$interval" ]; then
  echo "buffer <interval> <command...>"
  exit 1
fi

BUFFER=""
while true; do
  BUFFER="$(script -q -c "$2" /dev/null)"
  clear
  echo "$BUFFER"
  sleep "$1"
done
